# Generated by Django 3.2.9 on 2022-02-22 07:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='uploads/images')),
                ('price', models.IntegerField(default=100)),
                ('description', models.CharField(default='good', max_length=225)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gallary.category')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quntity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('Address', models.CharField(blank=True, default='', max_length=50)),
                ('phone', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallary.contact_info')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallary.products')),
            ],
        ),
    ]
